# export SPPN model to onnx

In [1]:
import torch.onnx
from torch.autograd import Variable
import torch.onnx
import torchvision
import numpy as np
# import onnx
# from torchviz import make_dot

import os, sys

from SPPE.src.main_fast_inference import InferenNet, InferenNet_fast
from dataloader import Mscoco

# pre-process
# pose_dataset = Mscoco();
# pose_model = InferenNet_fast(4*1+1, pose_dataset);
# pose_model.cuda();
# pose_model.eval();
# dummy_input = Variable(torch.randn(1, 3, 320, 256 ))
# dummy_input = torch.cat([dummy_input])
# dummy_input = dummy_input.to('cuda')

# # forword pass 
# y = pose_model(dummy_input)


In [3]:
# export
torch.onnx.export(pose_model, dummy_input, "pose.onnx")

NameError: name 'torch' is not defined

# Inspect model

In [ ]:
import onnx 
model_ins = onnx.load('pose.onnx')
onnx.checker.check_model(model_ins)

print(onnx.helper.printable_graph(model_ins.graph))

# Yolo3 model export (can't convert to mxnet)

In [2]:
def Yolov3_onnx():
    img = Variable(torch.randn(1, 3, 608, 608, ))
    dummy_input = torch.cat([img]) 
    
    ## model
    from yolo.darknet import Darknet
    det_model = Darknet("yolo/cfg/yolov3-spp.cfg") 
    det_model.load_weights('models/yolo/yolov3-spp.weights')
    det_model.net_info['height'] = 608
    det_model.cuda()
    det_model.eval()

    
    dummy_input = dummy_input.to('cuda')
    
    dummy_input.shape

    # visualize model
    y = det_model(dummy_input) 
#     make_dot(y.mean(), params=dict(det_model.named_parameters()z))
    
    # export onnx
    torch.onnx.export(det_model, dummy_input, "models/onnx/yolo.onnx")
Yolov3_onnx()

tensor([[[[ 6.4304e-01, -6.7735e-01,  1.8177e-01,  ..., -3.0819e-01,
            7.9924e-04, -2.0177e-01],
          [ 1.0102e+00, -4.0708e-01,  1.7394e-01,  ..., -9.8347e-02,
           -1.6340e-02, -5.3971e-01],
          [ 1.0935e+00, -6.2329e-01,  1.1606e-01,  ..., -1.1786e-01,
            2.8671e-01, -8.9447e-02],
          ...,
          [ 8.8378e-01,  1.8335e-01,  3.5810e-01,  ...,  2.7769e-01,
            8.1990e-02, -4.4701e-01],
          [ 1.0986e+00,  2.9783e-01,  5.2180e-01,  ...,  3.4212e-01,
            1.6830e-01, -3.6077e-01],
          [ 3.9581e-01,  2.8995e-01,  5.0885e-01,  ...,  2.7629e-01,
            1.2367e-02,  1.0208e-01]],

         [[ 2.5214e-01,  1.0909e+00,  9.5545e-01,  ...,  9.6304e-01,
            1.1588e+00,  3.5573e-01],
          [-3.6740e-01, -2.9637e-01, -3.8634e-01,  ..., -6.3594e-01,
           -3.2521e-01, -2.3730e-01],
          [-2.3794e-01, -7.9910e-02, -2.0064e-01,  ..., -5.8532e-01,
           -3.3167e-01, -1.9407e-01],
          ...,
     

tensor([[[[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         ...,

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1, 

tensor([[[[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         ...,

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1, 

tensor([[[[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         ...,

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1, 

tensor([[[[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         ...,

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1, 

tensor([[[[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1]],

         ...,

         [[ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          [ 1,  1,  1,  ...,  1,  1,  1],
          ...,
          [ 1,  1,  1,  ...,  1,  1, 

RuntimeError: /pytorch/torch/csrc/jit/tracer.h:120: getTracingState: Assertion `state` failed.